DROP TABLE region CASCADE;
DROP TABLE nation CASCADE;
DROP TABLE supplier CASCADE;
DROP TABLE customer CASCADE;
DROP TABLE part CASCADE;
DROP TABLE partsupp CASCADE;
DROP TABLE orders CASCADE;
DROP TABLE lineitem CASCADE;
